const SEVERITIES=new Set(["BLOCKING","MATERIAL","ADVISORY"]);
const FINDING_STATUSES=new Set(["OPEN","RESOLVED","REJECTED","SUPERSEDED"]);
const EVALUATION_OUTCOMES=new Set(["PASS","CHANGES_REQUIRED","ESCALATE"]);
function requiredString(v,n){if(typeof v!=="string"||!v.trim())throw new TypeError(`${n} must be a non-empty string`);return v.trim();}
function optionalString(v,n){return v==null?null:requiredString(v,n);}
function integer(v,n,min=0){if(!Number.isInteger(v)||v<min)throw new TypeError(`${n} must be an integer >= ${min}`);return v;}
function isoTimestamp(v,n){requiredString(v,n);const p=Date.parse(v);if(!Number.isFinite(p))throw new TypeError(`${n} must be an ISO timestamp`);return new Date(p).toISOString();}
function stringArray(v,n){if(!Array.isArray(v)||v.some(x=>typeof x!=="string"||!x.trim()))throw new TypeError(`${n} must be an array of non-empty strings`);return Object.freeze(v.map(x=>x.trim()));}
function enumValue(v,a,n){if(!a.has(v))throw new TypeError(`${n} must be one of ${[...a].join(", ")}`);return v;}
const immutable=r=>Object.freeze(r);
function snapshotCapabilityEpoch(e){if(!e||typeof e!=="object"||Array.isArray(e))throw new TypeError("capabilityEpoch is required");return immutable({provider:requiredString(e.provider,"capabilityEpoch.provider"),model:requiredString(e.model,"capabilityEpoch.model"),modelVersion:optionalString(e.modelVersion,"capabilityEpoch.modelVersion"),harnessVersion:optionalString(e.harnessVersion,"capabilityEpoch.harnessVersion"),promptSetVersion:optionalString(e.promptSetVersion,"capabilityEpoch.promptSetVersion")});}
function validateFindingSet(iterationId,findings){const target=requiredString(iterationId,"iterationId");if(!Array.isArray(findings))throw new TypeError("findings must be an array");const ids=new Set();for(const f of findings){if(!f||typeof f!=="object"||Array.isArray(f))throw new TypeError("each finding must be an object");const id=requiredString(f.id,"finding.id");if(ids.has(id))throw new Error(`duplicate finding id: ${id}`);ids.add(id);if(f.iterationId!==target)throw new Error(`finding ${id} belongs to iteration ${f.iterationId}, expected ${target}`);}return findings;}
export function createCapabilityEpoch({provider,model,modelVersion=null,harnessVersion=null,promptSetVersion=null}){return snapshotCapabilityEpoch({provider,model,modelVersion,harnessVersion,promptSetVersion});}
export function createIteration({id,artifactId,ordinal,candidateRef,createdAt,capabilityEpoch,parentIterationId=null}){const o=integer(ordinal,"ordinal",0),p=optionalString(parentIterationId,"parentIterationId");if(o===0&&p!==null)throw new TypeError("iteration 0 cannot have a parentIterationId");if(o>0&&p===null)throw new TypeError("iterations after 0 require parentIterationId");return immutable({id:requiredString(id,"id"),artifactId:requiredString(artifactId,"artifactId"),ordinal:o,candidateRef:requiredString(candidateRef,"candidateRef"),createdAt:isoTimestamp(createdAt,"createdAt"),capabilityEpoch:snapshotCapabilityEpoch(capabilityEpoch),parentIterationId:p});}
export function createFinding({id,iterationId,evaluatorId,severity,summary,evidenceRefs,status="OPEN",createdAt,supersedesFindingId=null}){return immutable({id:requiredString(id,"id"),iterationId:requiredString(iterationId,"iterationId"),evaluatorId:requiredString(evaluatorId,"evaluatorId"),severity:enumValue(severity,SEVERITIES,"severity"),summary:requiredString(summary,"summary"),evidenceRefs:stringArray(evidenceRefs,"evidenceRefs"),status:enumValue(status,FINDING_STATUSES,"status"),createdAt:isoTimestamp(createdAt,"createdAt"),supersedesFindingId:optionalString(supersedesFindingId,"supersedesFindingId")});}
export function createEvaluation({id,iterationId,evaluatorId,capabilityEpoch,outcome,findingIds,completedAt,critique}){return immutable({id:requiredString(id,"id"),iterationId:requiredString(iterationId,"iterationId"),evaluatorId:requiredString(evaluatorId,"evaluatorId"),capabilityEpoch:snapshotCapabilityEpoch(capabilityEpoch),outcome:enumValue(outcome,EVALUATION_OUTCOMES,"outcome"),findingIds:stringArray(findingIds,"findingIds"),completedAt:isoTimestamp(completedAt,"completedAt"),critique:requiredString(critique,"critique")});}
export function validateIterationLineage(iterations){if(!Array.isArray(iterations)||iterations.length===0)throw new TypeError("iterations must be a non-empty array");const byId=new Map(),byOrdinal=new Map();for(const i of iterations){if(byId.has(i.id))throw new Error(`duplicate iteration id: ${i.id}`);if(byOrdinal.has(i.ordinal))throw new Error(`duplicate iteration ordinal: ${i.ordinal}`);byId.set(i.id,i);byOrdinal.set(i.ordinal,i);}const roots=iterations.filter(i=>i.ordinal===0);if(roots.length!==1)throw new Error("exactly one iteration 0 is required");const artifactId=roots[0].artifactId,ordered=[...iterations].sort((a,b)=>a.ordinal-b.ordinal);for(let index=0;index<ordered.length;index++){const i=ordered[index];if(i.artifactId!==artifactId)throw new Error("all iterations in one lineage must share artifactId");if(i.ordinal!==index)throw new Error("iteration ordinals must be contiguous from 0");if(index===0)continue;const p=byId.get(i.parentIterationId);if(!p)throw new Error(`missing parent iteration: ${i.parentIterationId}`);if(p.id!==ordered[index-1].id)throw new Error("each iteration must directly follow the previous iteration");}return true;}
export function classifyEvaluation({iterationId,findings,authorityAllowsRepair=true}){validateFindingSet(iterationId,findings);const a=findings.filter(f=>f.status==="OPEN"&&(f.severity==="BLOCKING"||f.severity==="MATERIAL"));if(a.length===0)return immutable({decision:"STOP",reason:"NO_OPEN_BLOCKING_OR_MATERIAL_FINDINGS",actionableFindingIds:Object.freeze([])});if(!authorityAllowsRepair)return immutable({decision:"ESCALATE",reason:"REPAIR_EXCEEDS_CURRENT_AUTHORITY",actionableFindingIds:Object.freeze(a.map(f=>f.id))});return immutable({decision:"CONTINUE",reason:"OPEN_BLOCKING_OR_MATERIAL_FINDINGS",actionableFindingIds:Object.freeze(a.map(f=>f.id))});}
export function enforceManualRaiReviewPolicy({iterationId,findings,maxActionableFindings=3}){integer(maxActionableFindings,"maxActionableFindings",1);validateFindingSet(iterationId,findings);const a=findings.filter(f=>f.status==="OPEN"&&(f.severity==="BLOCKING"||f.severity==="MATERIAL"));if(a.length>maxActionableFindings)throw new Error(`manual RAI review may surface at most ${maxActionableFindings} open BLOCKING/MATERIAL findings per pass`);return true;}
export const RAI_CRITIQUE_PROMPT="What did the previous iteration add or retain that is unnecessary, speculative, redundant, or more complex than the simplest correct solution?";
