"""Neutral attention persistence, notification and explicit activation ports."""
from typing import Protocol
from pathlib import Path

from alienintent.control_plane.domain.attention import AttentionItem, AttentionOrigin, DeliveryReceipt, Resolution, StagedAttention
from alienintent.evidence_learning.domain.refs import Ref


class AttentionRepository(Protocol):
    def load(self, identity: str) -> tuple[int, dict[str, object], Ref]: ...
    def save(self, identity: str, expected_version: int, body: dict[str, object], source: Ref,
             actor: str, preceding: Ref | None) -> tuple[int, Ref]: ...
    def identities(self, prefix: str) -> tuple[str, ...]: ...
    def history(self, identity: str) -> tuple[dict[str, object], ...]: ...
    def validate_resolution(self, item: AttentionItem, decision: Resolution) -> None: ...


class AttentionNotifier(Protocol):
    def notify(self, item: AttentionItem, attempt_id: str) -> DeliveryReceipt | None: ...


class AttentionActivation(Protocol):
    def launch(self, item: AttentionItem) -> str: ...


class AttentionPort(Protocol):
    def ensure(self, origin: AttentionOrigin) -> AttentionItem: ...
    def seen(self, identity: str, actor: str, expected_version: int) -> AttentionItem: ...
    def resolve(self, identity: str, decision: Resolution) -> AttentionItem: ...


class AttentionMigration(Protocol):
    def stage(self, source: Path, *, permitted_root: Path, source_id: str) -> StagedAttention: ...
    def read(self, identity: str) -> dict[str, object]: ...
    def compare(self, identity: str, source: Path, *, permitted_root: Path) -> dict[str, object]: ...
    def rollback(self, identity: str) -> dict[str, object]: ...
