"""The service manager that owns the monitor host unit, and the supervisor's durable records."""
from typing import Protocol

from alienintent.control_plane.domain.monitor_host import HostBinding, HostOwnership, ManagerIdentity, UnitState


class HostManager(Protocol):
    """A service manager external to the model session. Every call either succeeds or raises."""

    def identity(self) -> ManagerIdentity: ...
    def unit_cgroup(self, manager: ManagerIdentity, binding: HostBinding) -> str: ...
    def show(self, unit: str) -> UnitState: ...
    def cgroup_empty(self, cgroup: str) -> bool: ...
    def launch(self, binding: HostBinding, argv: tuple[str, ...], environment: dict[str, str],
               stop_seconds: int | float, log_path: str) -> None: ...
    def observer_unit(self, binding: HostBinding) -> str: ...
    def arm_observer(self, binding: HostBinding, argv: tuple[str, ...], environment: dict[str, str],
                     period_seconds: int | float, log_path: str) -> str: ...
    def disarm_observer(self, binding: HostBinding) -> None: ...
    def kill(self, unit: str) -> None: ...
    def stop(self, unit: str) -> None: ...
    def reset_failed(self, unit: str) -> None: ...


class HostRecords(Protocol):
    """`monitor-host:<profile>`: history first, then the versioned pointer (compare-and-set)."""

    def read(self, profile: str) -> tuple[int, HostOwnership | None]: ...
    def save(self, expected_version: int, ownership: HostOwnership, observation: dict[str, object]) -> int: ...
    def history(self, profile: str) -> tuple[dict[str, object], ...]: ...


class HostAlerts(Protocol):
    """Durable external alert; one pending item per failed launch, deduplicated across observers."""

    def raise_alert(self, ownership: HostOwnership, reason: str, observation: dict[str, object]) -> str: ...
