"""Durable boundaries for one-writer cutover control (FX-E2)."""

from __future__ import annotations

from pathlib import Path
from typing import Callable, Mapping, Protocol


class WriterAuthorityStore(Protocol):
    def read(self) -> Mapping[str, object] | None: ...
    def create(self, record: Mapping[str, object]) -> None: ...
    def replace(self, expected_epoch: int, record: Mapping[str, object]) -> None: ...


class CheckpointStore(Protocol):
    def create(self, node_state: Path, python_store: Path, backup: Callable[[Path], None]) -> str: ...
    def verify(self, checkpoint: str) -> Mapping[str, object]: ...
    def node_state(self, checkpoint: str) -> bytes: ...


class NodeWriterObservation(Protocol):
    def live_node_writer(self) -> tuple[str, ...]: ...
    def pid_alive(self, pid: int) -> bool: ...
