"""Live repository boundary: metadata, issues and the published baseline, and the Issue writes `work link` makes."""

from __future__ import annotations

from typing import Mapping, Protocol


class RepositoryUnavailable(RuntimeError):
    """The repository could not be reached with the installation credential."""


class RepositoryRejected(ValueError):
    """The repository answer is incomplete or names a repository outside the profile."""


class RepositoryDirectory(Protocol):
    def metadata(self) -> Mapping[str, object]: ...
    def issues(self, limit: int = 10) -> tuple[Mapping[str, object], ...]: ...
    def issue(self, number: int) -> Mapping[str, object]: ...
    def create_issue(self, title: str, body: str) -> Mapping[str, object]: ...
    def update_issue(self, number: int, title: str, body: str) -> Mapping[str, object]: ...
    def close_issue(self, number: int, body: str) -> Mapping[str, object]: ...
    def recent_issues(self, limit: int) -> tuple[Mapping[str, object], ...]: ...
