#!/usr/bin/env python3
"""Read-only external bootstrap custody manifest (WO-220501, DAG node B0, proof fixture FX-B0).

Discovers the *current* external bootstrap directory rather than assuming the historical
eighteen-module list, records each asset's exact content identity, observable consumers
(sibling bootstrap assets, user service units, running processes, repository references) and
repository provenance, and assigns a per-asset custody class:

    KEEP_UNTIL_REPLACED            live protection/deployment; kept until a proven replacement
    HISTORICAL_PROVENANCE_UTILITY  retained Wave-1 evidence/proof utility; no live consumer
    REPLACEMENT_PROOF_CANDIDATE    an in-repository successor exists; live-boundary proof pending
    UNKNOWN                        custody undecided; blocks only this asset's own path

No class grants migration, deletion, service change, cutover or retirement authority. The pass
never imports or executes bootstrap code, never invokes systemctl, and proves it changed nothing
by snapshotting the bootstrap directory and unit directory before and after.

Usage:
    python3 tools/evidence/bootstrap_custody_manifest.py generate --output <manifest.json>
    python3 tools/evidence/bootstrap_custody_manifest.py check <manifest.json> [--root <dir>]
    python3 tools/evidence/bootstrap_custody_manifest.py controls --output <controls.json>
"""
from __future__ import annotations

import argparse
import copy
import datetime as dt
import hashlib
import json
import os
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
HOME = Path.home()
DEFAULT_BOOTSTRAP = HOME / ".local/share/alienintent-bootstrap"
DEFAULT_UNIT_DIR = HOME / ".config/systemd/user"

KEEP = "KEEP_UNTIL_REPLACED"
HISTORICAL = "HISTORICAL_PROVENANCE_UTILITY"
CANDIDATE = "REPLACEMENT_PROOF_CANDIDATE"
UNKNOWN = "UNKNOWN"
TAXONOMY = {
    KEEP: "Live protection or live deployment. Kept until its replacement is proven at the live boundary.",
    HISTORICAL: "Retained evidence/proof utility with no observed live consumer. Candidate for "
                "provenance-preserving repository custody, never blind deletion.",
    CANDIDATE: "An in-repository successor exists; the external copy stays until live-boundary "
               "replacement proof.",
    UNKNOWN: "Custody undecided. Blocks only this asset's own classification/replacement path.",
}

# Excluded: interpreter/test-runner caches regenerated by running the assets. They are still
# covered by the zero-effect snapshot.
EXCLUDED_DIRS = ("__pycache__", ".pytest_cache")

# The eighteen modules the Wave 2 B0 candidate was compiled against
# (docs/operations/post-wave1-program/prework/POSTW1-BOOTSTRAP-006-live-state.json).
HISTORICAL_EIGHTEEN = (
    "attention.py", "attention_wait.py", "cycle_data.py", "liveness.py", "notify_founder.py",
    "observer.py", "py05_py09_quality.py", "py05_py09_trajectory.py", "py10_preflight.py",
    "release_admission.py", "test_attention.py", "test_attention_wait.py", "test_cycle_data.py",
    "test_liveness_suppression.py", "test_notify_founder.py", "test_py10_preflight.py",
    "test_release_admission.py", "trajectory_consistency.py",
)

MATRIX = "docs/evidence/wave1-bootstrap-retirement-matrix.json"
REFRESH = "docs/evidence/2026-09-25-external-bootstrap-custody-refresh.md"
OPERATIONS = "docs/operations.md"
FDH_DOC = "docs/operations/factory-director-host.md"
FDH_INSTALLER = "tools/orchestration/install_factory_director_host.sh"
TRAJ_DOC = "docs/evidence/execution-trajectories/PY-05-to-PY-09-extraction-verification.md"


def _keep(group, basis, evidence, counterpart=None):
    return {"group": group, "class": KEEP, "basis": basis, "evidence": evidence,
            "counterpart": counterpart}


def _historical(group, basis, evidence):
    return {"group": group, "class": HISTORICAL, "basis": basis, "evidence": evidence}


def _unknown(group, basis, evidence, questions):
    return {"group": group, "class": UNKNOWN, "basis": basis, "evidence": evidence,
            "questions": questions}


_LIVENESS = "SWF-29 liveness reconciliation: " + MATRIX + " (KEEP_UNTIL_REPLACED); " + REFRESH
_ATTENTION = MATRIX + " mechanism 'attention queue'; " + OPERATIONS + " attention queue section"
_WAITER = MATRIX + " mechanism 'session-bound attention waiter'"
_NOTIFY = MATRIX + " mechanism 'Windows notification'; " + REFRESH
_FDH = "Installed by " + FDH_INSTALLER + " from repository source; unit alienintent-factory-director-host.service; " + FDH_DOC

POLICY = {
    "liveness.py": _keep(
        "liveness", "Temporary SWF-29 actor/effect liveness protection run by the alienintent-liveness user "
        "unit. Canonical SF-REQ-056 live replacement is not proven.", [MATRIX, REFRESH]),
    "test_liveness_suppression.py": _keep(
        "liveness", "Regression tests for the live liveness protection; they stay with their subject.",
        [MATRIX, "docs/decisions/2026-09-20-liveness-reconciliation.md"]),
    "observer.py": _keep(
        "observer", "SWF-27 deterministic lifecycle observer run by the alienintent-observer user unit. "
        "Canonical trajectory/monitor replacement is not proven.", [MATRIX, REFRESH]),
    "attention.py": _keep(
        "attention", "Attention queue library imported by liveness.py and observer.py. It is part of the "
        "current live protection chain. Identity/history/consumer migration is not proven.",
        [MATRIX, REFRESH, OPERATIONS]),
    "test_attention.py": _keep(
        "attention", "Regression tests for the live attention queue; they stay with their subject.",
        [MATRIX, OPERATIONS]),
    "attention_wait.py": _keep(
        "attention-wait", "Session-bound wake/attention bridge. Retirement is gated by successor "
        "attention handoff/tenure proof or an explicit decision.", [MATRIX, REFRESH, OPERATIONS]),
    "test_attention_wait.py": _keep(
        "attention-wait", "Regression tests for the attention waiter; they stay with their subject.", [MATRIX]),
    "notify_founder.py": _keep(
        "notification", "Bootstrap notification path imported by attention.py (live chain). Needs a separate "
        "notification risk/replacement disposition, which this pass does not decide.", [MATRIX, REFRESH]),
    "test_notify_founder.py": _keep(
        "notification", "Regression tests for the bootstrap notification path; they stay with their subject.",
        [MATRIX]),
    "release_admission.py": {
        "group": "release-admission", "class": CANDIDATE,
        "basis": "External release-admission gate. The canonical in-repository successor exists. The external "
                 "copy stays until the in-repo live-boundary replacement proof.",
        "evidence": [REFRESH, "docs/decisions/2026-09-20-wave1-release-coordinator.md",
                     "docs/evidence/brd-83-execution.md"],
        "counterpart": "tools/live/release_admission.py"},
    "test_release_admission.py": {
        "group": "release-admission", "class": CANDIDATE,
        "basis": "Tests for the external release-admission gate; the in-repository successor has its own "
                 "regression coverage.",
        "evidence": [REFRESH, "docs/evidence/brd-83-execution.md"],
        "counterpart": "tools/live/test_release_admission.py"},
    "cycle_data.py": _historical(
        "wave1-evidence-utilities", "Wave-1 repair-cycle evidence utility. No long-lived process or unit "
        "observed.", [REFRESH, MATRIX, OPERATIONS]),
    "test_cycle_data.py": _historical("wave1-evidence-utilities", "Tests for cycle_data.py.", [REFRESH, MATRIX]),
    "py05_py09_quality.py": _historical(
        "wave1-evidence-utilities", "Generator of the retained PY-05..PY-09 quality evidence.", [REFRESH, TRAJ_DOC]),
    "py05_py09_trajectory.py": _historical(
        "wave1-evidence-utilities", "Generator of the retained PY-05..PY-09 trajectory evidence.",
        [REFRESH, TRAJ_DOC]),
    "trajectory_consistency.py": _historical(
        "wave1-evidence-utilities", "Consistency checker for the retained PY-05..PY-09 evidence.",
        [REFRESH, TRAJ_DOC]),
    "py10_preflight.py": _historical(
        "wave1-evidence-utilities", "PY-10 sandbox preflight utility that produced the retained py10-preflight "
        "evidence.", [REFRESH, "docs/operations/py10-sandbox.md"]),
    "test_py10_preflight.py": _historical("wave1-evidence-utilities", "Tests for py10_preflight.py.", [REFRESH, MATRIX]),
    "factory-director-host/factory_director_host.py": _keep(
        "factory-director-host", "Live Factory Director Host process (a deployment, not a temporary "
        "protection). " + _FDH, [FDH_DOC, FDH_INSTALLER], "tools/orchestration/factory_director_host.py"),
    "factory-director-host/factory_director_inputs.py": _keep(
        "factory-director-host", "Imported by the live Factory Director Host. " + _FDH,
        [FDH_DOC, FDH_INSTALLER], "tools/orchestration/factory_director_inputs.py"),
    "factory-director-host/codex_session.py": _keep(
        "factory-director-host", "Provider session module of the live Factory Director Host. " + _FDH,
        [FDH_DOC, FDH_INSTALLER], "tools/orchestration/codex_session.py"),
    "factory-director-host/project_materialization.py": _keep(
        "factory-director-host", "Project materialization module installed for the live Factory Director Host "
        "from tools/live/project_materialization.py. " + _FDH, [FDH_DOC, FDH_INSTALLER],
        "tools/live/project_materialization.py"),
    "factory-director-host/factory-director-episode.md": _keep(
        "factory-director-host", "Episode prompt passed to the live Factory Director Host. " + _FDH,
        [FDH_DOC, FDH_INSTALLER], "tools/orchestration/factory-director-episode.md"),
    "factory-director-host/factory-director-host.sh": _keep(
        "factory-director-host", "ExecStart of alienintent-factory-director-host.service. It is generated by the "
        "installer's heredoc, so no repository file holds its exact bytes. " + _FDH,
        [FDH_DOC, FDH_INSTALLER, "tools/orchestration/systemd/alienintent-factory-director-host.service"]),
    "factory_status.sh": _unknown(
        "operator-shell-helpers", "Read-only operator snapshot helper. It is newly discovered and outside the "
        "historical eighteen. No service unit, process or repository code consumer was observed.", [REFRESH],
        ["No recorded owner, authority, replacement or expiry for this operator helper; its custody class "
         "(keep, repository custody or retirement decision) is undecided."]),
    "project_add_recovery_probe.sh": _unknown(
        "operator-shell-helpers", "Temporary GitHub Project add-path recovery probe. It is ExecStart of "
        "alienintent-project-add-probe.service, driven by alienintent-project-add-probe.timer. It creates and "
        "closes a disposable sandbox Issue on each run.", [REFRESH],
        ["No authority record for the probe or its expiry. The script states a RECOVERED exit condition, but "
         "no decision ties retirement to it.",
         "Timer activation state is not observable read-only here: no *.wants link is present and systemctl "
         "is not invoked by this inventory."]),
    "worker_credential_probe.sh": _unknown(
        "operator-shell-helpers", "Worker gh-credential probe. It proves pull-request refusal while the worker's "
        "operations succeed, and pushes and deletes a throwaway branch. It is cited as FDH-01 live-proof "
        "evidence. No service unit or process consumer was observed.",
        [REFRESH, "docs/evidence/fdh-01-live-proof/20260924T080401Z/08-output-A.json"],
        ["No recorded owner, authority or repository custody decision for this credential probe; whether it "
         "is live operations tooling or retained proof utility is undecided."]),
}

_READ_ONLY_GIT = {"grep", "ls-tree", "log", "rev-parse", "cat-file"}
# Read-only results keyed by argv; revisions are resolved to full SHAs before any keyed read.
_GIT_CACHE: dict[tuple, str] = {}


class Runner:
    """Records every subprocess; refuses anything but read-only git subcommands."""

    def __init__(self, repo: Path):
        self.repo = repo
        self.commands: list[list[str]] = []

    def git(self, *args: str) -> str:
        if not args or args[0] not in _READ_ONLY_GIT:
            raise PermissionError(f"refused non-read-only command: git {' '.join(args)}")
        argv = ["git", *args]
        self.commands.append(argv)
        key = (str(self.repo), tuple(argv))
        if key not in _GIT_CACHE or args[0] == "rev-parse":
            done = subprocess.run(argv, cwd=self.repo, capture_output=True, text=True)
            if not (done.returncode == 0 or (args[0] == "grep" and done.returncode == 1 and not done.stderr)):
                raise RuntimeError(f"{' '.join(argv)} failed ({done.returncode}): {done.stderr.strip()}")
            _GIT_CACHE[key] = done.stdout
        return _GIT_CACHE[key]


def _sha256(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _git_blob(data: bytes) -> str:
    return hashlib.sha1(b"blob %d\0" % len(data) + data).hexdigest()


def discover(root: Path) -> list[str]:
    found = []
    for dirpath, dirnames, filenames in os.walk(root):
        dirnames[:] = sorted(d for d in dirnames if d not in EXCLUDED_DIRS)
        for name in filenames:
            found.append((Path(dirpath) / name).relative_to(root).as_posix())
    return sorted(found)


def snapshot(*dirs: Path) -> dict:
    """Full state of each directory, caches included: type, mode, size, mtime_ns, sha256."""
    state = {}
    for base in dirs:
        if not base.exists():
            state[str(base)] = "ABSENT"
            continue
        for dirpath, dirnames, filenames in os.walk(base):
            dirnames.sort()
            for name in sorted(dirnames + filenames):
                p = Path(dirpath) / name
                st = p.lstat()
                entry = {"mode": st.st_mode, "mtime_ns": st.st_mtime_ns}
                if p.is_symlink():
                    entry["link"] = os.readlink(p)
                elif p.is_file():
                    entry |= {"size": st.st_size, "sha256": _sha256(p.read_bytes())}
                state[str(p)] = entry
    return state


def _digest(value) -> str:
    return "sha256:" + _sha256(json.dumps(value, sort_keys=True, separators=(",", ":")).encode())


def _units(unit_dir: Path) -> tuple[dict[str, str], set[str]]:
    units, enabled = {}, set()
    if not unit_dir.is_dir():
        return units, enabled
    for p in sorted(unit_dir.iterdir()):
        if p.is_file() and not p.is_symlink():
            units[p.name] = p.read_text(errors="replace")
        elif p.is_dir() and p.name.endswith(".wants"):
            enabled.update(child.name for child in p.iterdir())
    return units, enabled


def _processes(proc_root: Path) -> list[dict] | str:
    if not proc_root.is_dir():
        return "UNKNOWN: process table not readable"
    rows = []
    for p in proc_root.iterdir():
        if not p.name.isdigit() or int(p.name) == os.getpid():
            continue
        try:
            argv = [a for a in (p / "cmdline").read_bytes().decode(errors="replace").split("\0") if a]
        except OSError:
            continue
        rows.append({"pid": int(p.name), "argv": argv})
    return sorted(rows, key=lambda r: r["pid"])


def _references(rel: str, text_by_asset: dict[str, str]) -> list[str]:
    name = Path(rel).name
    stem = Path(rel).stem
    pattern = re.compile(rf"(^|\W)(import\s+{re.escape(stem)}\b|from\s+{re.escape(stem)}\s+import\b)|"
                         rf"(?<![\w-]){re.escape(name)}", re.M)
    return sorted(other for other, text in text_by_asset.items()
                  if other != rel and pattern.search(text))


def _classify(rel: str, observed: dict, head_paths: set[str], policy: dict) -> dict:
    entry = policy.get(rel)
    if entry is None:
        return {"class": UNKNOWN, "group": "unclassified", "evidence": [],
                "basis": "Discovered asset with no custody policy entry.",
                "unknowns": [{"question": "No custody evidence or decision exists for this newly discovered asset.",
                              "blocks": [rel]}],
                "migration_deletion_retirement_authorized": False}
    if entry["class"] not in TAXONOMY:
        raise ValueError(f"{rel}: policy class {entry['class']!r} is outside the custody taxonomy")
    custody = {k: entry[k] for k in ("class", "group", "basis", "evidence")}
    custody["unknowns"] = [{"question": q, "blocks": [rel]} for q in entry.get("questions", [])]
    live = observed["service_units"] or observed["processes"]
    if entry["class"] == HISTORICAL and live:
        custody["class"] = UNKNOWN
        custody["unknowns"].append({"question": "Policy says historical, but a live consumer (service unit or "
                                    "process) was observed; the conflict must be resolved.", "blocks": [rel]})
    counterpart = entry.get("counterpart")
    if counterpart:
        custody["replacement_ref"] = counterpart
        if entry["class"] == CANDIDATE and counterpart not in head_paths:
            custody["class"] = UNKNOWN
            custody["unknowns"].append({"question": f"Named successor {counterpart} is absent at the pinned "
                                        "repository revision.", "blocks": [rel]})
    if custody["class"] == UNKNOWN and not custody["unknowns"]:
        custody["unknowns"].append({"question": "Custody undecided.", "blocks": [rel]})
    custody["migration_deletion_retirement_authorized"] = False
    return custody


def generate(root: Path = DEFAULT_BOOTSTRAP, unit_dir: Path = DEFAULT_UNIT_DIR, proc_root: Path = Path("/proc"),
             repo: Path = ROOT, revision: str = "HEAD", policy: dict | None = None,
             clock=lambda: dt.datetime.now(dt.timezone.utc), during=None) -> dict:
    policy = POLICY if policy is None else policy
    runner = Runner(repo)
    before = snapshot(root, unit_dir)
    started = clock()

    rev = runner.git("rev-parse", revision).strip()
    head_blobs: dict[str, list[str]] = {}
    for line in runner.git("ls-tree", "-r", rev).splitlines():
        meta, path = line.split("\t", 1)
        head_blobs.setdefault(meta.split()[2], []).append(path)
    head_paths = {p for paths in head_blobs.values() for p in paths}

    paths = discover(root)
    data = {rel: (root / rel).read_bytes() for rel in paths}
    text = {rel: raw.decode(errors="replace") for rel, raw in data.items()}
    units, enabled = _units(unit_dir)
    procs = _processes(proc_root)
    root_s = str(root)

    if during is not None:
        during(root)

    blobs = {rel: _git_blob(raw) for rel, raw in data.items()}
    history: dict[str, list[dict]] = {}
    commit = None
    for line in runner.git("log", "--raw", "--no-abbrev", "--no-renames", "--format=C %H %s", rev).splitlines():
        if line.startswith("C "):
            sha, _, subject = line[2:].partition(" ")
            commit = {"commit": sha, "subject": subject}
        elif line.startswith(":") and commit:
            for blob in line.split("\t", 1)[0].split()[2:4]:
                touched = history.setdefault(blob, [])
                if not touched or touched[-1] is not commit:
                    touched.append(commit)

    names = sorted({Path(rel).name for rel in paths} | {f"alienintent-bootstrap/{rel}" for rel in paths})
    mentions: dict[str, set[str]] = {}
    grep_args = ["grep", "-o", "-F"] + [a for n in names for a in ("-e", n)] + [rev, "--"]
    for line in runner.git(*grep_args).splitlines():
        _, path, match = line.split(":", 2)
        mentions.setdefault(match, set()).add(path)

    assets = []
    for rel in paths:
        raw = data[rel]
        abs_path = f"{root_s}/{rel}"
        unit_refs = []
        for unit, body in units.items():
            expanded = body.replace("%h", str(HOME)).replace("~/", f"{HOME}/")
            lines = [ln.strip() for ln in expanded.splitlines() if abs_path in ln]
            if lines:
                unit_refs.append({"unit": unit, "enabled_via_wants_link": unit in enabled, "lines": lines})
        proc_refs = procs if isinstance(procs, str) else [p for p in procs if abs_path in p["argv"]]
        qualified = f"alienintent-bootstrap/{rel}"
        repo_refs = sorted(mentions.get(qualified, set()))
        basename_mentions = mentions.get(Path(rel).name, set()) | set(repo_refs)
        blob = blobs[rel]
        bootstrap_refs = _references(rel, text)
        observed = {"service_units": unit_refs, "processes": proc_refs if isinstance(proc_refs, list) else []}
        custody = _classify(rel, observed, head_paths, policy)
        if custody.get("replacement_ref"):
            ref = custody["replacement_ref"]
            custody["replacement_ref_status"] = ("ABSENT" if ref not in head_paths else
                                                 "IDENTICAL" if ref in head_blobs.get(blob, []) else "DIFFERS")
        st = (root / rel).stat()
        assets.append({
            "path": rel,
            "absolute_path": abs_path,
            "in_historical_eighteen": rel in HISTORICAL_EIGHTEEN,
            "identity": {"sha256": _sha256(raw), "git_blob": blob, "size": len(raw),
                         "mode": oct(st.st_mode & 0o7777),
                         "mtime_utc": dt.datetime.fromtimestamp(st.st_mtime, dt.timezone.utc).isoformat()},
            "consumers": {
                "bootstrap_assets": bootstrap_refs,
                "service_units": unit_refs,
                "processes": proc_refs,
                "repository_qualified_references": {
                    "code": [p for p in repo_refs if not p.startswith("docs/")],
                    "docs": [p for p in repo_refs if p.startswith("docs/")]},
                "repository_basename_mentions_unattributed": len(basename_mentions),
            },
            "provenance": {
                "repository_paths_with_identical_bytes": sorted(head_blobs.get(blob, [])),
                "repository_commits_touching_blob": history.get(blob, []),
                "bootstrap_tests": [r for r in bootstrap_refs if Path(r).name.startswith("test_")],
            },
            "custody": custody,
        })

    after = snapshot(root, unit_dir)
    discovered = set(paths)
    summary = {cls: sum(1 for a in assets if a["custody"]["class"] == cls) for cls in TAXONOMY}
    return {
        "schema_version": "1",
        "artifact_type": "bootstrap_custody_manifest",
        "work_unit": "WO-220501",
        "issue": "AlienLogicLab/alienintent#116",
        "proof_fixture": "FX-B0",
        "status": "READ_ONLY_INVENTORY; NO MIGRATION, DELETION, SERVICE CHANGE, CUTOVER OR RETIREMENT AUTHORITY",
        "provenance": {
            "generated_at": started.isoformat(),
            "generator": "tools/evidence/bootstrap_custody_manifest.py",
            "generator_sha256": _sha256(Path(__file__).read_bytes()),
            "repository_revision": rev,
            "bootstrap_root": root_s,
            "unit_dir": str(unit_dir),
            "process_table": str(proc_root),
            "observation_limits": [
                "Process and unit observations are a point-in-time readback on the producing host.",
                "Unit activation is inferred only from *.wants links; systemctl is never invoked.",
                "Repository basename mentions may collide with unrelated files, so they are counted, not attributed.",
                "mtime is recorded for context only; identity is sha256 and git blob.",
            ],
        },
        "taxonomy": TAXONOMY,
        "discovery": {
            "excluded_cache_dirs": list(EXCLUDED_DIRS),
            "discovered_count": len(paths),
            "historical_eighteen_present": sorted(discovered & set(HISTORICAL_EIGHTEEN)),
            "historical_eighteen_missing": sorted(set(HISTORICAL_EIGHTEEN) - discovered),
            "additional_to_historical_eighteen": sorted(discovered - set(HISTORICAL_EIGHTEEN)),
            "policy_entries_not_discovered": sorted(set(policy) - discovered),
        },
        "assets": assets,
        "summary": summary,
        "side_effect_check": {
            "scope": [root_s, str(unit_dir)],
            "before_digest": _digest(before),
            "after_digest": _digest(after),
            "unchanged": before == after,
            "changed_paths": sorted(k for k in set(before) | set(after) if before.get(k) != after.get(k)),
            "commands_executed": runner.commands,
        },
    }


def check_manifest(manifest: dict) -> list[str]:
    failures = []
    if manifest.get("artifact_type") != "bootstrap_custody_manifest":
        failures.append("artifact_type: not a bootstrap_custody_manifest")
    assets = manifest.get("assets") or []
    if not assets:
        failures.append("assets: empty inventory")
    paths = [a.get("path") for a in assets]
    if len(set(paths)) != len(paths):
        failures.append("assets: duplicate paths")
    for a in assets:
        rel = a.get("path", "<unnamed>")
        ident = a.get("identity", {})
        if not re.fullmatch(r"[0-9a-f]{64}", str(ident.get("sha256", ""))):
            failures.append(f"identity: {rel} lacks an exact sha256")
        if not re.fullmatch(r"[0-9a-f]{40}", str(ident.get("git_blob", ""))):
            failures.append(f"identity: {rel} lacks a git blob id")
        custody = a.get("custody", {})
        cls = custody.get("class")
        if cls not in TAXONOMY:
            failures.append(f"custody_class: {rel} has {cls!r}, not one of {tuple(TAXONOMY)}")
            continue
        if custody.get("migration_deletion_retirement_authorized") is not False:
            failures.append(f"no_invented_authority: {rel} claims migration/deletion/retirement authority")
        for unknown in custody.get("unknowns", []):
            if unknown.get("blocks") != [rel]:
                failures.append(f"unknown_locality: {rel} unknown blocks {unknown.get('blocks')}, not only itself")
        if cls == UNKNOWN and not custody.get("unknowns"):
            failures.append(f"unknown_explicit: {rel} is UNKNOWN without a stated unknown")
        if cls != UNKNOWN and not (custody.get("basis") and custody.get("evidence")):
            failures.append(f"classification_evidence: {rel} is {cls} without basis and evidence")
        consumers = a.get("consumers", {})
        if cls == HISTORICAL and (consumers.get("service_units") or consumers.get("processes")):
            failures.append(f"truthful_class: {rel} is historical despite an observed live consumer")
        if cls == CANDIDATE and not custody.get("replacement_ref"):
            failures.append(f"truthful_class: {rel} is a replacement candidate without a named successor")
    disc = manifest.get("discovery", {})
    present = set(paths)
    for name in HISTORICAL_EIGHTEEN:
        if name not in present and name not in disc.get("historical_eighteen_missing", []):
            failures.append(f"discovery: historical module {name} neither inventoried nor reported missing")
    if sorted(present - set(HISTORICAL_EIGHTEEN)) != disc.get("additional_to_historical_eighteen"):
        failures.append("discovery: additional-asset list disagrees with the inventory")
    if disc.get("discovered_count") != len(assets):
        failures.append("discovery: discovered_count disagrees with the inventory")
    summary = {cls: sum(1 for a in assets if a.get("custody", {}).get("class") == cls) for cls in TAXONOMY}
    if manifest.get("summary") != summary:
        failures.append("summary: class counts disagree with the inventory")
    effects = manifest.get("side_effect_check", {})
    if effects.get("unchanged") is not True or effects.get("before_digest") != effects.get("after_digest"):
        failures.append(f"zero_effect: inventory pass changed {effects.get('changed_paths')}")
    for argv in effects.get("commands_executed", []):
        if argv[:1] != ["git"] or len(argv) < 2 or argv[1] not in _READ_ONLY_GIT:
            failures.append(f"zero_effect: non-read-only command recorded {argv}")
    return failures


def verify_against_root(manifest: dict, root: Path) -> list[str]:
    """Rediscover root and compare path set and content identity with the manifest."""
    failures = []
    recorded = {a["path"]: a["identity"]["sha256"] for a in manifest.get("assets", [])}
    current = {rel: _sha256((root / rel).read_bytes()) for rel in discover(root)}
    for rel in sorted(set(current) - set(recorded)):
        failures.append(f"completeness: discovered asset {rel} is missing from the manifest")
    for rel in sorted(set(recorded) - set(current)):
        failures.append(f"completeness: manifest asset {rel} no longer exists")
    for rel in sorted(set(recorded) & set(current)):
        if recorded[rel] != current[rel]:
            failures.append(f"identity: {rel} sha256 differs from current bytes")
    return failures


# --- FX-B0 negative controls: one discriminating control per material failure class -------------

def build_fixture(base: Path) -> tuple[Path, Path, Path, dict]:
    """Disposable bootstrap tree, unit dir and process table shaped like the real surface."""
    root, units, proc = base / "bootstrap", base / "units", base / "proc"
    (root / "factory-director-host").mkdir(parents=True)
    (root / "__pycache__").mkdir()
    (root / "__pycache__" / "attention.cpython-312.pyc").write_bytes(b"\0cache")
    for name in HISTORICAL_EIGHTEEN:
        (root / name).write_text(f"# {name}\n")
    (root / "liveness.py").write_text("import attention\n")
    (root / "test_liveness_suppression.py").write_text("import liveness\n")
    (root / "factory_status.sh").write_text("#!/usr/bin/env bash\n")
    (root / "factory-director-host" / "factory_director_host.py").write_text("print('host')\n")
    (units / "default.target.wants").mkdir(parents=True)
    (units / "alienintent-liveness.service").write_text(f"[Service]\nExecStart=/usr/bin/python3 {root}/liveness.py\n")
    (units / "default.target.wants" / "alienintent-liveness.service").symlink_to(units / "alienintent-liveness.service")
    (proc / "4242").mkdir(parents=True)
    (proc / "4242" / "cmdline").write_bytes(b"/usr/bin/python3\0" + f"{root}/liveness.py".encode() + b"\0")
    policy = {k: v for k, v in POLICY.items() if k in HISTORICAL_EIGHTEEN}
    policy["factory-director-host/factory_director_host.py"] = POLICY["factory-director-host/factory_director_host.py"]
    return root, units, proc, policy


_FIXED_CLOCK = lambda: dt.datetime(2026, 9, 26, tzinfo=dt.timezone.utc)  # noqa: E731


def _fixture_manifest(base: Path, **kwargs) -> tuple[dict, Path]:
    root, units, proc, policy = build_fixture(base)
    return generate(root, units, proc, ROOT, "HEAD", policy, _FIXED_CLOCK, **kwargs), root


def run_negative_controls() -> list[dict]:
    def touch(root: Path) -> None:
        (root / "observer.py").write_text("# rewritten during inventory\n")

    def drop_additional(m: dict) -> None:
        m["assets"] = [a for a in m["assets"] if a["path"] != "factory_status.sh"]

    def tamper_hash(m: dict) -> None:
        m["assets"][0]["identity"]["sha256"] = "0" * 64

    def invent_retirement(m: dict) -> None:
        a = next(a for a in m["assets"] if a["path"] == "liveness.py")
        a["custody"]["class"] = "RETIRE_CANDIDATE"

    def widen_unknown(m: dict) -> None:
        a = next(a for a in m["assets"] if a["path"] == "factory_status.sh")
        a["custody"]["unknowns"][0]["blocks"].append("liveness.py")

    controls = [
        ("discovery_beyond_historical_eighteen", "fixed-list inventory omits a newly discovered asset",
         drop_additional, "verify", "completeness"),
        ("exact_identity", "recorded sha256 no longer matches the asset bytes", tamper_hash, "verify", "identity"),
        ("truthful_custody_class", "live protection relabelled with an invented retirement class",
         invent_retirement, "check", "custody_class"),
        ("unknown_locality", "UNKNOWN for one asset widened to block an unrelated asset",
         widen_unknown, "check", "unknown_locality"),
        ("zero_effect", "an asset is rewritten during the inventory pass", None, "check", "zero_effect"),
    ]
    records = []
    for control_id, fault, mutate, gate, expected in controls:
        with tempfile.TemporaryDirectory() as tmp:
            intact, root = _fixture_manifest(Path(tmp) / "intact")
            gate_fn = (lambda m: check_manifest(m) + verify_against_root(m, root)) if gate == "verify" else check_manifest
            intact_failures = gate_fn(intact)
            if mutate is None:
                faulted, _ = _fixture_manifest(Path(tmp) / "fault", during=touch)
                fault_failures = check_manifest(faulted)
            else:
                faulted = copy.deepcopy(intact)
                mutate(faulted)
                fault_failures = gate_fn(faulted)
            restored, root = _fixture_manifest(Path(tmp) / "restored")
            restored_failures = gate_fn(restored)
        detected = any(f.startswith(expected + ":") for f in fault_failures)
        records.append({
            "control": control_id, "fault": fault, "gate": gate, "expected_failure_check": expected,
            "applications": 1,
            "intact": {"passed": not intact_failures, "failures": intact_failures},
            "fault_result": {"detected": detected, "failures": fault_failures},
            "restored": {"passed": not restored_failures, "failures": restored_failures},
            "verdict": "PASS" if (not intact_failures and detected and not restored_failures) else "FAIL",
        })
    return records


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    sub = parser.add_subparsers(dest="cmd", required=True)
    g = sub.add_parser("generate")
    g.add_argument("--root", type=Path, default=DEFAULT_BOOTSTRAP)
    g.add_argument("--unit-dir", type=Path, default=DEFAULT_UNIT_DIR)
    g.add_argument("--revision", default="HEAD")
    g.add_argument("--output", type=Path)
    c = sub.add_parser("check")
    c.add_argument("manifest", type=Path)
    c.add_argument("--root", type=Path, help="also rediscover this live root and compare")
    n = sub.add_parser("controls")
    n.add_argument("--output", type=Path)
    args = parser.parse_args(argv)

    if args.cmd == "generate":
        manifest = generate(args.root, args.unit_dir, revision=args.revision)
        body = json.dumps(manifest, indent=2, sort_keys=True) + "\n"
        if args.output:
            args.output.write_text(body)
        failures = check_manifest(manifest)
        print(json.dumps({"assets": len(manifest["assets"]), "summary": manifest["summary"],
                          "unchanged": manifest["side_effect_check"]["unchanged"], "failures": failures}, indent=2))
        return 1 if failures else 0
    if args.cmd == "check":
        manifest = json.loads(args.manifest.read_text())
        failures = check_manifest(manifest)
        if args.root:
            failures += verify_against_root(manifest, args.root)
        print(json.dumps({"result": "FAIL" if failures else "PASS", "failures": failures}, indent=2))
        return 1 if failures else 0
    records = run_negative_controls()
    body = json.dumps({"fixture": "FX-B0", "controls": records}, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.write_text(body)
    print(body, end="")
    return 0 if all(r["verdict"] == "PASS" for r in records) else 1


if __name__ == "__main__":
    raise SystemExit(main())
